// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Parsed is a decoded payload split into fields. Kind is one of epc, wifi,
 * vcard, event, geo, tel, sms, email, crypto, url or text; Fields holds
 * only what the payload carries. It is the inverse of the Format*
 * functions, so a round trip returns the same values.
 */
export interface Parsed {
    "kind": string;
    "fields"?: { [_ in string]?: string } | null;
}
