// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BarcodeApp is the main service struct exposed to the Wails v3 frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CopyToClipboard copies text (e.g. raw SVG or string) to the native OS clipboard.
 */
export function CopyToClipboard(text: string): $CancellablePromise<boolean> {
    return $Call.ByID(1411264089, text);
}

/**
 * ExportBatchToFolder exports generated batch barcodes into a target directory.
 */
export function ExportBatchToFolder(req: $models.BatchExportRequest): $CancellablePromise<$models.BatchExportResponse> {
    return $Call.ByID(1829561616, req);
}

/**
 * FormatEvent formats event parameters into iCal/vCalendar QR data format.
 */
export function FormatEvent(opts: $models.EventInput): $CancellablePromise<string> {
    return $Call.ByID(2432037614, opts);
}

/**
 * FormatVCard formats contact parameters into vCard 3.0 standard QR data format.
 */
export function FormatVCard(opts: $models.VCardInput): $CancellablePromise<string> {
    return $Call.ByID(1596215682, opts);
}

/**
 * FormatWifi formats Wi-Fi connection parameters into standard QR data format.
 */
export function FormatWifi(opts: $models.WifiInput): $CancellablePromise<string> {
    return $Call.ByID(3458962879, opts);
}

/**
 * GenerateBarcode generates SVG and PNG representations of a single barcode.
 */
export function GenerateBarcode(req: $models.BarcodeRequest): $CancellablePromise<$models.BarcodeResult> {
    return $Call.ByID(2834328570, req);
}

/**
 * GenerateBatch processes multiple lines of text and generates barcodes for each.
 */
export function GenerateBatch(req: $models.BatchBarcodeRequest): $CancellablePromise<$models.BatchBarcodeResponse> {
    return $Call.ByID(1822436222, req);
}

/**
 * GetVersion returns the current application version.
 */
export function GetVersion(): $CancellablePromise<string> {
    return $Call.ByID(2309158169);
}

/**
 * PickExportFolder opens a native folder selection dialog.
 */
export function PickExportFolder(): $CancellablePromise<string> {
    return $Call.ByID(1083076046);
}

/**
 * PickTextFile opens a native open-file dialog for .txt or .csv files and reads all lines.
 */
export function PickTextFile(): $CancellablePromise<[string, string[] | null]> {
    return $Call.ByID(161843409);
}

/**
 * SaveSingleFile opens a native save-file dialog and writes the given SVG or PNG content.
 */
export function SaveSingleFile(req: $models.SaveSingleFileRequest): $CancellablePromise<string> {
    return $Call.ByID(4267146450, req);
}
