// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BarcodeApp is the main service struct exposed to the Wails v3 frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CopyToClipboard copies text (e.g. raw SVG or string) to the native OS clipboard.
 */
export function CopyToClipboard(text: string): $CancellablePromise<boolean> {
    return $Call.ByID(3783022343, text);
}

/**
 * ExportBatchToFolder exports generated batch barcodes into a target directory.
 */
export function ExportBatchToFolder(req: $models.BatchExportRequest): $CancellablePromise<$models.BatchExportResponse> {
    return $Call.ByID(697745266, req);
}

/**
 * FormatCrypto formats cryptocurrency payment parameters into standard URI format.
 */
export function FormatCrypto(opts: $models.CryptoInput): $CancellablePromise<string> {
    return $Call.ByID(2436130509, opts);
}

/**
 * FormatEPC formats SEPA credit transfer parameters into EPC-QR-Code (GiroCode).
 */
export function FormatEPC(opts: $models.EPCInput): $CancellablePromise<string> {
    return $Call.ByID(1712079574, opts);
}

/**
 * FormatEmail formats email address, subject and body into RFC 6068 mailto URI.
 */
export function FormatEmail(opts: $models.EmailInput): $CancellablePromise<string> {
    return $Call.ByID(432479156, opts);
}

/**
 * FormatEvent formats event parameters into iCal/vCalendar QR data format.
 */
export function FormatEvent(opts: $models.EventInput): $CancellablePromise<string> {
    return $Call.ByID(2251355188, opts);
}

/**
 * FormatGeo formats latitude, longitude and search query into RFC 5870 geo URI.
 */
export function FormatGeo(opts: $models.GeoInput): $CancellablePromise<string> {
    return $Call.ByID(1301610169, opts);
}

/**
 * FormatSMS formats phone number and message into smsto URI.
 */
export function FormatSMS(opts: $models.SMSInput): $CancellablePromise<string> {
    return $Call.ByID(1447939993, opts);
}

/**
 * FormatTel formats telephone dialing number into RFC 3966 tel URI.
 */
export function FormatTel(opts: $models.TelInput): $CancellablePromise<string> {
    return $Call.ByID(997924401, opts);
}

/**
 * FormatVCard formats contact parameters into vCard 3.0 standard QR data format.
 */
export function FormatVCard(opts: $models.VCardInput): $CancellablePromise<string> {
    return $Call.ByID(939783500, opts);
}

/**
 * FormatWifi formats Wi-Fi connection parameters into standard QR data format.
 */
export function FormatWifi(opts: $models.WifiInput): $CancellablePromise<string> {
    return $Call.ByID(1953257241, opts);
}

/**
 * GenerateBarcode generates SVG and PNG representations of a single barcode.
 */
export function GenerateBarcode(req: $models.BarcodeRequest): $CancellablePromise<$models.BarcodeResult> {
    return $Call.ByID(3245091200, req);
}

/**
 * GenerateBatch processes multiple lines of text and generates barcodes for each.
 */
export function GenerateBatch(req: $models.BatchBarcodeRequest): $CancellablePromise<$models.BatchBarcodeResponse> {
    return $Call.ByID(3453167428, req);
}

/**
 * GetVersion returns the current application version.
 */
export function GetVersion(): $CancellablePromise<string> {
    return $Call.ByID(3771792143);
}

/**
 * PickExportFolder opens a native folder selection dialog.
 */
export function PickExportFolder(): $CancellablePromise<string> {
    return $Call.ByID(512332088);
}

/**
 * PickTextFile opens a native open-file dialog for .txt or .csv files and reads all lines.
 */
export function PickTextFile(): $CancellablePromise<[string, string[] | null]> {
    return $Call.ByID(2658359795);
}

/**
 * SaveSingleFile opens a native save-file dialog and writes the given SVG or PNG content.
 */
export function SaveSingleFile(req: $models.SaveSingleFileRequest): $CancellablePromise<string> {
    return $Call.ByID(2139578368, req);
}
