// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BarcodeRequest contains parameters for generating a single barcode.
 */
export interface BarcodeRequest {
    /**
     * qr, datamatrix, code128, code39, ean13, ean8, upca, itf
     */
    "type": string;

    /**
     * Content / text to encode
     */
    "data": string;

    /**
     * Optional custom caption text to show below barcode
     */
    "customText": string;

    /**
     * Output width in px (0 for default)
     */
    "width": number;

    /**
     * Output height in px (0 for default)
     */
    "height": number;

    /**
     * Show readable text below barcode
     */
    "showText": boolean;

    /**
     * Foreground color (e.g. #000000)
     */
    "foregroundColor": string;

    /**
     * Background color (e.g. #ffffff or transparent)
     */
    "backgroundColor": string;
}

/**
 * BarcodeResult holds the generated barcode content and metadata.
 */
export interface BarcodeResult {
    "type": string;
    "data": string;

    /**
     * Raw SVG XML
     */
    "svg"?: string;

    /**
     * Base64 data URI (data:image/png;base64,...)
     */
    "pngData"?: string;
    "success": boolean;
    "error"?: string;
}

/**
 * BatchBarcodeRequest for bulk barcode generation.
 */
export interface BatchBarcodeRequest {
    "type": string;
    "lines": string[] | null;
    "width": number;
    "height": number;
    "showText": boolean;
    "foregroundColor": string;
    "backgroundColor": string;
}

/**
 * BatchBarcodeResponse summarizes batch generation results.
 */
export interface BatchBarcodeResponse {
    "items": BatchItemResult[] | null;
    "total": number;
    "validCount": number;
    "errorCount": number;
}

/**
 * BatchExportRequest for exporting generated batch items to a folder.
 */
export interface BatchExportRequest {
    "folderPath": string;

    /**
     * "index", "data_slug", "data_raw"
     */
    "namingScheme": string;

    /**
     * Optional prefix, e.g. "barcode_"
     */
    "prefix": string;

    /**
     * "svg" or "png"
     */
    "format": string;
    "items": BatchItemResult[] | null;
}

/**
 * BatchExportResponse returns the outcome of folder export.
 */
export interface BatchExportResponse {
    "exportedCount": number;
    "skippedCount": number;
    "savedPaths": string[] | null;
    "error"?: string;
}

/**
 * BatchItemResult holds the result for one item in a batch.
 */
export interface BatchItemResult {
    "index": number;
    "data": string;
    "svg"?: string;
    "pngData"?: string;
    "success": boolean;
    "error"?: string;
}

/**
 * CryptoInput contains options for cryptocurrency payment QR codes.
 */
export interface CryptoInput {
    /**
     * bitcoin, ethereum, solana, etc.
     */
    "coin": string;
    "address": string;
    "amount": number;
    "label": string;
    "message": string;
}

/**
 * EPCInput contains options for EPC-QR-Codes (GiroCode / SEPA-Überweisung).
 */
export interface EPCInput {
    "name": string;
    "iban": string;
    "bic": string;
    "amount": number;
    "reference": string;
    "purpose": string;
}

/**
 * EmailInput contains email parameters (mailto:).
 */
export interface EmailInput {
    "to": string;
    "subject": string;
    "body": string;
}

/**
 * EventInput contains options for iCal/vCalendar QR codes.
 */
export interface EventInput {
    "summary": string;

    /**
     * YYYYMMDDTHHMMSS
     */
    "startTime": string;
    "endTime": string;
    "timeZone": string;
}

/**
 * GeoInput contains latitude and longitude coordinates for map navigation QR codes.
 */
export interface GeoInput {
    "latitude": number;
    "longitude": number;
    "query": string;
}

/**
 * SMSInput contains SMS message parameters.
 */
export interface SMSInput {
    "phoneNumber": string;
    "message": string;
}

/**
 * SaveSingleFileRequest for saving one barcode to disk.
 */
export interface SaveSingleFileRequest {
    "defaultName": string;

    /**
     * "svg" or "png"
     */
    "format": string;

    /**
     * Raw SVG or Base64 PNG
     */
    "content": string;
}

/**
 * TelInput contains telephone dialing parameters.
 */
export interface TelInput {
    "phoneNumber": string;
}

/**
 * VCardInput contains options for contact vCard 3.0 QR codes.
 */
export interface VCardInput {
    "firstName": string;
    "lastName": string;
    "email": string;
    "phone": string;
}

/**
 * WifiInput contains options for Wi-Fi QR codes.
 */
export interface WifiInput {
    "ssid": string;
    "password": string;

    /**
     * WPA, WEP, nopass
     */
    "encryption": string;
    "hidden": boolean;
}
