// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as qrformats$0 from "../qrformats/models.js";

/**
 * BarcodeRequest contains parameters for generating a single barcode.
 */
export interface BarcodeRequest {
    /**
     * qr, datamatrix, code128, code39, ean13, ean8, upca, itf
     */
    "type": string;

    /**
     * Content / text to encode
     */
    "data": string;

    /**
     * Optional custom caption text to show below barcode
     */
    "customText": string;

    /**
     * Output width in px (0 for default)
     */
    "width": number;

    /**
     * Output height in px (0 for default)
     */
    "height": number;

    /**
     * Show readable text below barcode
     */
    "showText": boolean;

    /**
     * Caption size in px (0 = automatic)
     */
    "fontSize": number;

    /**
     * Foreground color (e.g. #000000)
     */
    "foregroundColor": string;

    /**
     * Background color (e.g. #ffffff or transparent)
     */
    "backgroundColor": string;
}

/**
 * BarcodeResult holds the generated barcode content and metadata.
 */
export interface BarcodeResult {
    "type": string;
    "data": string;

    /**
     * Raw SVG XML
     */
    "svg"?: string;

    /**
     * Base64 data URI (data:image/png;base64,...)
     */
    "pngData"?: string;
    "success": boolean;

    /**
     * ReadBack is the result of reading the generated PNG with the decoder:
     * "ok", "mismatch" (read something else), "unreadable" (e.g. too little
     * contrast) or "unsupported" (no reader for the symbology yet).
     */
    "readBack"?: string;

    /**
     * English text (fallback)
     */
    "error"?: string;
    "errorCode"?: string;
    "errorParams"?: { [_ in string]?: string } | null;
}

/**
 * BatchBarcodeRequest for bulk barcode generation.
 */
export interface BatchBarcodeRequest {
    "type": string;
    "lines": string[] | null;
    "width": number;
    "height": number;
    "showText": boolean;
    "fontSize": number;
    "foregroundColor": string;
    "backgroundColor": string;
}

/**
 * BatchBarcodeResponse summarizes batch generation results.
 */
export interface BatchBarcodeResponse {
    "items": BatchItemResult[] | null;
    "total": number;
    "validCount": number;
    "errorCount": number;
}

/**
 * BatchExportRequest for exporting generated batch items to a folder.
 */
export interface BatchExportRequest {
    "folderPath": string;

    /**
     * "index", "data_slug", "data_raw"
     */
    "namingScheme": string;

    /**
     * Optional prefix, e.g. "barcode_"
     */
    "prefix": string;

    /**
     * "svg" or "png"
     */
    "format": string;
    "items": BatchItemResult[] | null;
}

/**
 * BatchExportResponse returns the outcome of folder export.
 */
export interface BatchExportResponse {
    "exportedCount": number;
    "skippedCount": number;
    "savedPaths": string[] | null;
    "error"?: string;
}

/**
 * BatchItemResult holds the result for one item in a batch.
 */
export interface BatchItemResult {
    "index": number;
    "data": string;
    "svg"?: string;
    "pngData"?: string;
    "success": boolean;
    "error"?: string;
    "errorCode"?: string;
    "errorParams"?: { [_ in string]?: string } | null;
}

/**
 * CryptoInput contains options for cryptocurrency payment QR codes.
 */
export interface CryptoInput {
    /**
     * bitcoin, ethereum, solana, etc.
     */
    "coin": string;
    "address": string;
    "amount": number;
    "label": string;
    "message": string;
}

/**
 * DecodeImageResult is the answer of DecodeImage.
 */
export interface DecodeImageResult {
    "success": boolean;
    "codes": DecodedCode[] | null;
    "width": number;
    "height": number;
    "error"?: string;
    "errorCode"?: string;
    "errorParams"?: { [_ in string]?: string } | null;
}

/**
 * DecodedCode is one barcode found by DecodeImage.
 */
export interface DecodedCode {
    "type": string;
    "text": string;

    /**
     * known payload split into fields
     */
    "content"?: qrformats$0.Parsed | null;

    /**
     * in image pixels
     */
    "points"?: Point[] | null;
}

/**
 * EPCInput contains options for EPC-QR-Codes (GiroCode / SEPA-Überweisung).
 */
export interface EPCInput {
    "name": string;
    "iban": string;
    "bic": string;
    "amount": number;
    "reference": string;
    "purpose": string;
}

/**
 * EmailInput contains email parameters (mailto:).
 */
export interface EmailInput {
    "to": string;
    "subject": string;
    "body": string;
}

/**
 * EventInput contains options for iCal/vCalendar QR codes.
 */
export interface EventInput {
    "summary": string;

    /**
     * YYYYMMDDTHHMMSS
     */
    "startTime": string;
    "endTime": string;
    "timeZone": string;
}

/**
 * GeoInput contains latitude and longitude coordinates for map navigation QR codes.
 */
export interface GeoInput {
    "latitude": number;
    "longitude": number;
    "query": string;
}

/**
 * Point is a position in image pixels.
 */
export interface Point {
    "x": number;
    "y": number;
}

/**
 * RetailValidation is the live check of an EAN-13, EAN-8 or UPC-A input.
 * Reason is "", "non_digit", "length" or "checksum"; the GUI words it.
 */
export interface RetailValidation {
    /**
     * false for types without check digit
     */
    "applies": boolean;
    "valid": boolean;
    "reason": string;

    /**
     * complete / corrected code
     */
    "code": string;
    "checkDigitAdded": boolean;
    "given": number;
    "expected": number;
    "minLength": number;
    "maxLength": number;
}

/**
 * SMSInput contains SMS message parameters.
 */
export interface SMSInput {
    "phoneNumber": string;
    "message": string;
}

/**
 * SaveSingleFileRequest for saving one barcode to disk.
 */
export interface SaveSingleFileRequest {
    "defaultName": string;

    /**
     * "svg" or "png"
     */
    "format": string;

    /**
     * Raw SVG or Base64 PNG
     */
    "content": string;
}

/**
 * TableFile is an imported TXT/CSV file. Every row has at least one cell:
 * cell 0 is the barcode content, cell 1 (optional) a caption.
 */
export interface TableFile {
    "path": string;

    /**
     * "" = one column per line
     */
    "separator": string;
    "rows": (string[] | null)[] | null;
}

/**
 * TelInput contains telephone dialing parameters.
 */
export interface TelInput {
    "phoneNumber": string;
}

/**
 * VCardInput contains options for contact vCard 3.0 QR codes.
 */
export interface VCardInput {
    "firstName": string;
    "lastName": string;
    "email": string;
    "phone": string;
}

/**
 * WifiInput contains options for Wi-Fi QR codes.
 */
export interface WifiInput {
    "ssid": string;
    "password": string;

    /**
     * WPA, WEP, nopass
     */
    "encryption": string;
    "hidden": boolean;
}
